title: Jeetu
tagline: cat /var/log/life
email: i.am.jeetu2@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  /var/log/life
# baseurl: ""
baseurl: "/me" # the subpath of your site, e.g. /blog
url: "https://github.com/i-am-jeetu" # the base hostname & protocol for your site, e.g. http://example.com
 
github_username:  i-am-jeetu
paginate: 10 #Number of posts in a page

permalink:        pretty
future: true 
paginate_path: "me/page:num/"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
feed:
  path: atom.xml
exclude: ["readme.md"]

github:
  repo: https://github.com/i-am-jeetu



# Github's Recommneded Settings (We can Ignore this)
lsi: false
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
